module.exports = {
  parserOptions: {
    ecmaVersion: "2015",
    sourceType: "module"
  },
  rules: {
    "no-undef": "error",
    "no-restricted-globals": [
      "error",
      "Infinity",
      "NaN",
      "undefined",
      "globalThis",
      "eval",
      "uneval",
      "isFinite",
      "isNaN",
      "parseFloat",
      "parseInt",
      "encodeURI",
      "encodeURIComponent",
      "decodeURI",
      "decodeURIComponent",
      "escape",
      "unescape",
      "Object",
      "Function",
      "Boolean",
      "Symbol",
      "Error",
      "Number",
      "BigInt",
      "Math",
      "Date",
      "String",
      "RegExp",
      "Array",
      "Map",
      "Set",
      "WeakMap",
      "WeakSet",
      "ArrayBuffer",
      "SharedArrayBuffer",
      "Atomics",
      "DataView",
      "JSON",
      "Promise",
      "Generator",
      "GeneratorFunction",
      "AsyncFunction",
      "AsyncGenerator",
      "AsyncGeneratorFunction",
      "Reflect",
      "Proxy",
      "Intl",
      "WebAssembly"
    ]
  }
};
