packages:
  - sandbox
minimumReleaseAge: 2160 # 36 hours
minimumReleaseAgeExclude:
  - "@adobe/alloy"
  - "@adobe/aep-rules-engine"
onlyBuiltDependencies:
  - msw
  - esbuild
verifyDepsBeforeRun: warn
