packages:
  - sandboxes/*
  - packages/*
linkWorkspacePackages: true
minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - "@adobe/alloy"
  - "@adobe/aep-rules-engine"
onlyBuiltDependencies:
  - msw
  - esbuild
verifyDepsBeforeRun: warn
