packages:
  - .
  - sandboxes/*
  - packages/*
  - packages/reactor-extension/scripts/helpers/parcel-transformer-extension-name
linkWorkspacePackages: true
minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - "@adobe/alloy"
  - "@adobe/alloy-core"
  - "@adobe/aep-rules-engine"
onlyBuiltDependencies:
  - msw
  - esbuild
verifyDepsBeforeRun: warn
