const AUTH_STATES = {
  AMBIGUOUS: "ambiguous",
  AUTHENTICATED: "authenticated",
  LOGGEDOUT: "loggedOut"
};

const COOKIE_NAMES = {
  CUSTOMER_ID_HASH: "CIDH",
  EXPERIENCE_CLOUD_ID: "ECID",
  ID_SYNC_TIMESTAMP: "idSyncTimestamp",
  ID_SYNC_CONTROL: "idSyncControl"
};

const DEFAULT_ID_SYNC_TTL_MINUTES = 10080; // 7 days

export { AUTH_STATES, COOKIE_NAMES, DEFAULT_ID_SYNC_TTL_MINUTES };
