const AUTH_STATES = {
  UNKNOWN: 0,
  AUTHENTICATED: 1,
  LOGGED_OUT: 2
};

const COOKIE_NAMES = {
  CUSTOMER_ID_HASH: "CIDH",
  EXPERIENCE_CLOUD_ID: "ECID",
  ID_SYNC_TIMESTAMP: "idSyncTimestamp",
  ID_SYNC_CONTROL: "idSyncControl"
};

export { AUTH_STATES, COOKIE_NAMES };
