export const RENDERED = "RENDERED";
export const PARTIALLY_RENDERED = "PARTIALLY_RENDERED";
export const NON_RENDERABLE = "NON_RENDERABLE";
export const FAILED_TO_RENDER = "FAILED_TO_RENDER";
export const NOT_RENDERED = "NOT_RENDERED";
export const SUCCEEDED_TO_RENDER = "SUCCEEDED_TO_RENDER";
