name: Publish To NPM
on: workflow_dispatch

jobs:
  publish-to-npm:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node.js version
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: "Publish to NPM"
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
