name: Publish To NPM
on: workflow_dispatch

jobs:
  publish-to-npm:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.0
          run_install: false
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: "~/.pnpm-store"
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ secrets.NPM_CACHE_VERSION }} # increment NPM_CACHE_VERSION secret to force cache reset
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: "Publish to NPM"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          access: "public"
