name: Samples Deploy
on:
  push:
    branches:
      -main
  pull_request:
jobs:
  deploy:
    name: "Deploy"
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cd samples && npm ci && npm run init
    - name: Run deploy script
      run: node samples/deploy.js
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}



