name: Alloyio Performance Test

on:
  push:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run sitespeed.io performance test
        run: npx sitespeed.io https://alloyio.com --budget.config=./report/budget.json --outputFolder=./report

      - name: Upload performance report
        uses: actions/upload-artifact@v2
        with:
          name: Performance Report
          path: report
