apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 4
metadata:
  name: Alloy SDK Int ee-pre-prd
rootDir: ./
env:
  ALLOY_ENV: int
  EDGE_BASE_PATH: ee-pre-prd
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 3.6.0
speed: 1
pageLoadTimeout: 3000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - parse-uri
    - node-fetch
    - js-cookie
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-object-assign"
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
suites:
  - name: "Edge"
    browserName: "microsoftedge"
    headless: true
    browserVersion: "119"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
    excludedTestFiles:
      [
        "test/functional/specs/Personalization/C782718.js",
        "test/functional/specs/Privacy/C5594870.js",
      ]
  - name: "Safari"
    browserName: "safari"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "macOS 13"
    excludedTestFiles:
      [
        "test/functional/specs/Personalization/C205528.js",
        "test/functional/specs/Identity/C6842981.js",
        "test/functional/specs/Privacy/IAB/C224677.js",
        "test/functional/specs/Privacy/C5594870.js",
        "test/functional/specs/LibraryInfo/C2589.js",
      ]
  - name: "Firefox"
    browserName: "firefox"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
    excludedTestFiles: ["test/functional/specs/Privacy/C5594870.js"]
  - name: "Chrome"
    browserName: "chrome"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
    excludedTestFiles:
      [
        "test/functional/specs/Privacy/C5594870.js",
        "test/functional/specs/Personalization/C7494472.js",
      ]
