apiVersion: v1alpha
kind: testcafe
showConsoleLog: true
defaults:
  mode: sauce
sauce:
  region: us-west-1
  sauceignore: .sauceignore
metadata:
  name: Alloy SDK Int ee-pre-prd
  tags:
    - e2e
  build: Release $CI_COMMIT_SHORT_SHA
rootDir: ./
env:
  ALLOY_ENV: int
  EDGE_BASE_PATH: ee-pre-prd
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 2.3.1
speed: 0.05
pageLoadTimeout: 3000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-object-assign"
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
suites:
  - name: "Firefox"
    platformName: "Windows 11"
    browserName: "firefox"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Audiences/C12412.js",
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Personalization/C7638574.js",
        "test/functional/specs/Personalization/C9932846.js",
        "test/functional/specs/Personalization/C205528.js",
        "test/functional/specs/Personalization/C7494472.js",
      ]

  - name: "Chrome"
    shard: concurrency
    platformName: "Windows 11"
    browserName: "chrome"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Audiences/C12412.js",
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Personalization/C7638574.js",
        "test/functional/specs/Personalization/C9932846.js",
        "test/functional/specs/Personalization/C205528.js",
        "test/functional/specs/Personalization/C7494472.js",
      ]

  - name: "Edge"
    shard: concurrency
    platformName: "Windows 11"
    browserName: "microsoftedge"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Audiences/C12412.js",
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Personalization/C7638574.js",
        "test/functional/specs/Personalization/C9932846.js",
        "test/functional/specs/Personalization/C205528.js",
        "test/functional/specs/Personalization/C7494472.js",
      ]

  - name: "Safari"
    shard: concurrency
    platformName: "macOS 12"
    browserName: "safari"
    browserVersion: "latest"
    env:
      ALLOY_ENV: int
      EDGE_BASE_PATH: ee-pre-prd
      NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Audiences/C12412.js",
        "test/functional/specs/LibraryInfo/C2589.js",
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Personalization/C7638574.js",
        "test/functional/specs/Personalization/C9932846.js",
        "test/functional/specs/Personalization/C205528.js",
        "test/functional/specs/Personalization/C7494472.js",
      ]
