apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 4
metadata:
  name: Alloy SDK Int ee-pre-prd
rootDir: ./
env:
  ALLOY_ENV: int
  EDGE_BASE_PATH: ee-pre-prd
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 3.5.0
speed: 1
pageLoadTimeout: 3000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - parse-uri
    - js-cookie
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-object-assign"
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
suites:
  - &defaultSuite
    headless: true
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      - "test/functional/specs/Privacy/C5594870.js"
  - <<: *defaultSuite
    name: "Edge"
    browserName: "microsoftedge"
    browserVersion: "119"
    platformName: "Windows 11"
    excludedTestFiles:
      - "test/functional/specs/Personalization/C782718.js"
      - "test/functional/specs/Privacy/C5594870.js"
      - "test/functional/specs/Personalization/C8631577.js"
  - <<: *defaultSuite
    name: "Safari"
    browserName: "safari"
    browserVersion: "latest"
    platformName: "macOS 13"
    excludedTestFiles:
      - "test/functional/specs/Personalization/C205528.js"
      - "test/functional/specs/Identity/C6842981.js"
      - "test/functional/specs/Privacy/IAB/C224677.js"
      - "test/functional/specs/Privacy/C5594870.js"
      - "test/functional/specs/LibraryInfo/C2589.js"
  - <<: *defaultSuite
    name: "Firefox"
    browserName: "firefox"
    browserVersion: "latest"
    platformName: "macOS 13"
  - <<: *defaultSuite
    name: "Chrome"
    browserName: "chrome"
    browserVersion: "latest"
    platformName: "Windows 11"
    excludedTestFiles:
      - "test/functional/specs/Privacy/C5594870.js"
      - "test/functional/specs/Personalization/C7494472.js"
      - "test/functional/specs/Personalization/C8631576.js"
      - "test/functional/specs/Personalization/C8631577.js"