apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  concurrency: 4
metadata:
  name: Alloy SDK Int ee-pre-prd
rootDir: ./
env:
  ALLOY_ENV: int
  EDGE_BASE_PATH: ee-pre-prd
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 3.6.0
nodeVersion: "22"
speed: 1
pageLoadTimeout: 5000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - parse-uri
    - js-cookie
    - read-cache
    - uuid
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
suites:
  - name: "Safari"
    browserName: "safari"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "macOS 13"
    excludedTestFiles:
      [
        "test/functional/specs/Personalization/C205528.js",
        "test/functional/specs/Identity/C6842981.js",
        "test/functional/specs/Consent/IAB/C224677.js",
        "test/functional/specs/Consent/C5594870.js",
        "test/functional/specs/LibraryInfo/C2589.js",
      ]
  - name: "Firefox"
    browserName: "firefox"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
    excludedTestFiles: ["test/functional/specs/Consent/C5594870.js"]
  # - name: "Chrome"
    # browserName: "chrome"
    # headless: true
    # browserVersion: "latest"
    # src:
    #   - "test/functional/specs/**/*.js"
    # platformName: "Windows 11"
    # excludedTestFiles:
    #   [
    #     "test/functional/specs/Consent/C5594870.js",
    #     "test/functional/specs/Personalization/C7494472.js",
    #     "test/functional/specs/Personalization/C8631576.js",
    #     "test/functional/specs/Personalization/C8631577.js",
    #   ]