apiVersion: v1alpha
kind: testcafe
defaults:
  mode: sauce
sauce:
  region: us-west-1
metadata:
  name: Testing TestCafe Support
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
concurrency: 30
quarantineMode:
  attemptLimit: 5
  successThreshold: 3
docker:
  fileTransfer: mount
showConsoleLog: true
disablePageCaching: true
testcafe:
  version: 2.0.0
reporters:
  junit:
    enabled: true
    filename: saucectl-report.xml
env:
  ALLOY_ENV: prod
  ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
  NPM_PACKAGE_VERSION: $ALLOY_PROD_VERSION
rootDir: ./
suites:
  - name: "Firefox Latest | Windows 11"
    mode: sauce
    browserName: "firefox"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
