apiVersion: v1alpha
kind: testcafe
showConsoleLog: true
sauce:
  region: us-west-1
  retries: 2
metadata:
  name: Alloy SDK Prod pre-prod-upstreams
rootDir: ./
env:
  ALLOY_ENV: prod
  EDGE_BASE_PATH: pre-prod-upstreams
  ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 3.6.0
nodeVersion: "22"
speed: 1
pageLoadTimeout: 3000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - parse-uri
    - js-cookie
    - read-cache
    - uuid
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
suites:
  - name: "Edge"
    browserName: "microsoftedge"
    headless: true
    browserVersion: "119"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
    excludedTestFiles:
      [
        "test/functional/specs/Personalization/C782718.js",
        "test/functional/specs/Consent/C5594870.js",
        "test/functional/specs/Personalization/C8631577.js",
      ]
  - name: "Safari"
    browserName: "safari"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "macOS 13"
    excludedTestFiles:
      [
        "test/functional/specs/Personalization/C205528.js",
        "test/functional/specs/Identity/C6842981.js",
        "test/functional/specs/Consent/IAB/C224677.js",
        "test/functional/specs/Consent/C5594870.js",
        "test/functional/specs/LibraryInfo/C2589.js",
      ]
  - name: "Firefox"
    browserName: "firefox"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
    excludedTestFiles: ["test/functional/specs/Consent/C5594870.js"]
  - name: "Chrome"
    browserName: "chrome"
    headless: true
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
    excludedTestFiles:
      [
        "test/functional/specs/Consent/C5594870.js",
        "test/functional/specs/Personalization/C7494472.js",
        "test/functional/specs/Personalization/C8631576.js",
        "test/functional/specs/Personalization/C8631577.js",
      ]
