apiVersion: v1alpha
kind: testcafe
showConsoleLog: true
defaults:
  mode: sauce
sauce:
  region: us-west-1
  sauceignore: .sauceignore
  retries: 4
metadata:
  name: Alloy SDK Prod Functional Test
  tags:
    - e2e
  build: Release $CI_COMMIT_SHORT_SHA
rootDir: ./
env:
  ALLOY_ENV: prod
  ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 1.19.0
speed: 0.05
pageLoadTimeout: 3000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-object-assign"
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
suites:
  - name: "Edge"
    shard: concurrency
    platformName: "Windows 11"
    browserName: "microsoftedge"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles: [ "test/functional/specs/Privacy/C1576777.js" ]
