apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
  retries: 3
metadata:
  name: Alloy Prod
rootDir: ./
env:
  ALLOY_ENV: prod
  ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
  PACKAGE_VERSION: $PACKAGE_VERSION
testcafe:
  version: "package.json"
nodeVersion: "$NODE_VERSION"
speed: 0.5
pageLoadTimeout: 8000
disablePageCaching: false
timeZone: New_York
npm:
  dependencies:
    - node-fetch
    - parse-uri
    - js-cookie
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
    - "@adobe/reactor-object-assign"
suites:
  - name: "Chrome"
    smartRetry:
      failedOnly: true
    browserName: "chrome"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "Windows 11"
    excludedTestFiles:
      [
        "test/functional/specs/Data Collector/C81182.js",
        "test/functional/specs/Consent/C5594870.js",
        "test/functional/specs/Personalization/C7494472.js",
        "test/functional/specs/Consent/C1576777.js",
        "test/functional/specs/Audiences/C12411.js",
        "test/functional/specs/Audiences/C31436.js",
      ]

showConsoleLog: true