apiVersion: v1alpha
kind: testcafe
showConsoleLog: true
defaults:
  mode: sauce
sauce:
  region: us-west-1
  sauceignore: .sauceignore
  retries: 3
metadata:
  name: Alloy SDK Prod Functional Test
  tags:
    - e2e
  build: Release $CI_COMMIT_SHORT_SHA
rootDir: ./
env:
  ALLOY_ENV: prod
  ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 2.2.0
pageLoadTimeout: 1000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-object-assign"
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
suites:
  - name: "Safari"
    shard: concurrency
    platformName: "macOS 11.00"
    browserVersion: "14"
    browserName: "safari"
    env:
      ALLOY_ENV: prod
      ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
      NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/LibraryInfo/C2589.js"
      ]
