apiVersion: v1alpha
kind: testcafe
defaults:
  mode: sauce
sauce:
  region: us-west-1
  sauceignore: .sauceignore
  concurrency: 2
metadata:
  name: Alloy SDK Prod Functional Test
  tags:
    - e2e
  build: Release $CI_COMMIT_SHORT_SHA
rootDir: ./
env:
  ALLOY_ENV: prod
  ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 2.1.0
speed: 0.01
quarantineMode:
  attemptLimit: 10
  successThreshold: 1
timeZone: New_York
npm:
  dependencies:
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-object-assign"
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
suites:
  - name: "Chrome"
    shard: concurrency
    platformName: "Windows 11"
    browserName: "chrome"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Personalization/C205528.js",
      ]

  - name: "Firefox"
    shard: concurrency
    platformName: "Windows 11"
    browserName: "firefox"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Personalization/C205528.js",
      ]

  - name: "Edge"
    shard: concurrency
    platformName: "Windows 11"
    browserName: "microsoftedge"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Personalization/C205528.js",
      ]

  - name: "Safari"
    shard: concurrency
    platformName: "macOS 12"
    browserName: "safari"
    browserVersion: "latest"
    env:
      ALLOY_ENV: prod
      ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
      NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles:
      [
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Context/C2598.js",
        "test/functional/specs/LibraryInfo/C2589.js",
        "test/functional/specs/Personalization/C205528.js",
      ]
