apiVersion: v1alpha
kind: testcafe
defaults:
  mode: sauce
sauce:
  region: us-west-1
  sauceignore: .sauceignore
  concurrency: 1
metadata:
  name: Alloy SDK Prod Functional Test
  tags:
    - e2e
  build: Release $CI_COMMIT_SHORT_SHA
rootDir: ./
docker:
  fileTransfer: copy
  image: saucelabs/stt-testcafe-node:latest
env:
  ALLOY_ENV: prod
  ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: 1.19.0
speed: 0.01
disablePageCaching: true
retryTestPages: true
timeZone: New_York
npm:
  dependencies:
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-object-assign"
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
suites:
  - name: "Safari"
    shard: concurrency
    platformName: "macOS 12"
    browserName: "safari"
    browserVersion: "latest"
    env:
      ALLOY_ENV: prod
      ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
      NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
    src:
      - "test/functional/specs/**/*.js"
    excludedTestFiles: [ "test/functional/specs/Privacy/C1576777.js", "test/functional/specs/Personalization/C205528.js"]
