apiVersion: v1alpha
kind: testcafe
sauce:
  region: us-west-1
metadata:
  name: Alloy Prod
rootDir: ./
env:
  ALLOY_ENV: prod
  ALLOY_PROD_VERSION: $ALLOY_PROD_VERSION
  NPM_PACKAGE_VERSION: $NPM_PACKAGE_VERSION
testcafe:
  version: "package.json"
nodeVersion: "$NODE_VERSION"
speed: 1
pageLoadTimeout: 3000
disablePageCaching: true
timeZone: New_York
npm:
  dependencies:
    - node-fetch
    - parse-uri
    - js-cookie
    - read-cache
    - uuid
    - css.escape
    - "@adobe/reactor-load-script"
    - "@adobe/reactor-cookie"
    - "@adobe/reactor-query-string"
    - "@adobe/reactor-promise"
    - "@adobe/reactor-object-assign"
suites:
  - name: "Safari"
    browserName: "safari"
    browserVersion: "latest"
    src:
      - "test/functional/specs/**/*.js"
    platformName: "macOS 13"
    excludedTestFiles:
      [
        "test/functional/specs/Privacy/C1472435.js",
        "test/functional/specs/Data Collector/C81182.js",
        "test/functional/specs/Personalization/C205528.js",
        "test/functional/specs/Identity/C6842981.js",
        "test/functional/specs/Privacy/IAB/C224677.js",
        "test/functional/specs/Privacy/C5594870.js",
        "test/functional/specs/LibraryInfo/C2589.js",
        "test/functional/specs/Privacy/C1576777.js",
        "test/functional/specs/Audiences/C12411.js",
        "test/functional/specs/Audiences/C31436.js",
        "test/functional/specs/Personalization/C8631576.js",
        "test/functional/specs/Personalization/C8631577.js",
      ]
      
showConsoleLog: true